<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PluginImporterTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
    <PackageReference Include="FakeItEasy" Version="7.3.1" />
    <PackageReference Include="FluentAssertions" Version="6.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Application.csproj" />
    <ProjectReference Include="..\..\SharedLibraryCore\SharedLibraryCore.csproj" />
    <ProjectReference Include="..\..\Data\Data.csproj" />
    <ProjectReference Include="..\..\WebfrontCore\WebfrontCore.csproj" />
    <!-- <ProjectReference Include="..\..\Plugins\Stats\Stats.csproj" /> -->
  </ItemGroup>

</Project>
